//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowDemo2.Client.DocumentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Done {
            get {
                return this.DoneField;
            }
            set {
                if ((this.DoneField.Equals(value) != true)) {
                    this.DoneField = value;
                    this.RaisePropertyChanged("Done");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service")]
    [System.SerializableAttribute()]
    public partial class DocumentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentServiceReference.IDocumentService")]
    public interface IDocumentService {
        
        // CODEGEN: Generating message contract since the operation CreateDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/CreateDocument", ReplyAction="http://tempuri.org/IDocumentService/CreateDocumentResponse")]
        WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentResponse CreateDocument(WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/UpdateDocument", ReplyAction="http://tempuri.org/IDocumentService/UpdateDocumentResponse")]
        WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentResponse UpdateDocument(WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service", Order=0)]
        public WorkFlowDemo2.Client.DocumentServiceReference.Document Document;
        
        public CreateDocumentRequest() {
        }
        
        public CreateDocumentRequest(WorkFlowDemo2.Client.DocumentServiceReference.Document Document) {
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service", Order=0)]
        public WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse DocumentResponse;
        
        public CreateDocumentResponse() {
        }
        
        public CreateDocumentResponse(WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse DocumentResponse) {
            this.DocumentResponse = DocumentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service", Order=0)]
        public WorkFlowDemo2.Client.DocumentServiceReference.Document Document;
        
        public UpdateDocumentRequest() {
        }
        
        public UpdateDocumentRequest(WorkFlowDemo2.Client.DocumentServiceReference.Document Document) {
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkFlowDemo1.Service", Order=0)]
        public WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse DocumentResponse;
        
        public UpdateDocumentResponse() {
        }
        
        public UpdateDocumentResponse(WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse DocumentResponse) {
            this.DocumentResponse = DocumentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService>, WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentResponse WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService.CreateDocument(WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentRequest request) {
            return base.Channel.CreateDocument(request);
        }
        
        public WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse CreateDocument(WorkFlowDemo2.Client.DocumentServiceReference.Document Document) {
            WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentRequest inValue = new WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentRequest();
            inValue.Document = Document;
            WorkFlowDemo2.Client.DocumentServiceReference.CreateDocumentResponse retVal = ((WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService)(this)).CreateDocument(inValue);
            return retVal.DocumentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentResponse WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService.UpdateDocument(WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentRequest request) {
            return base.Channel.UpdateDocument(request);
        }
        
        public WorkFlowDemo2.Client.DocumentServiceReference.DocumentResponse UpdateDocument(WorkFlowDemo2.Client.DocumentServiceReference.Document Document) {
            WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentRequest inValue = new WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentRequest();
            inValue.Document = Document;
            WorkFlowDemo2.Client.DocumentServiceReference.UpdateDocumentResponse retVal = ((WorkFlowDemo2.Client.DocumentServiceReference.IDocumentService)(this)).UpdateDocument(inValue);
            return retVal.DocumentResponse;
        }
    }
}
