//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VisualStudio.BizTalkProject.Generators, Version 4.0.30319.42000.
// 
namespace FKMessaging.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SuppServiceSoap", Namespace="http://tempuri.org/")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://localhost/supplierservice/service1.asmx")]
    public partial class SuppService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SuppService() {
            this.Url = "http://localhost/supplierservice/service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostOrder(SuppOrder order) {
            this.Invoke("PostOrder", new object[] {
                        order});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostOrder(SuppOrder order, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostOrder", new object[] {
                        order}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostOrder(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SuppOrder {
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string customerPONumber;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ItemId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Quantity;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Priority;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string OrderDate;
    }
}
