//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.CloudServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudServiceReference.WcfService_CustomerBizTalkService")]
    public interface WcfService_CustomerBizTalkService {
        
        // CODEGEN: Generating message contract since the operation Operation_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientConsole.CloudServiceReference.Operation_1Response Operation_1(ClientConsole.CloudServiceReference.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CustomerBizTalkService.GetCustomerNumerRequest")]
    public partial class GetCustomerNumerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CustomerBizTalkService.GetCustomerNumerResponse")]
    public partial class GetCustomerNumerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerNumberField;
        
        private bool customerNumberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerNumberSpecified {
            get {
                return this.customerNumberFieldSpecified;
            }
            set {
                this.customerNumberFieldSpecified = value;
                this.RaisePropertyChanged("CustomerNumberSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CustomerBizTalkService.GetCustomerNumerRequest", Order=0)]
        public ClientConsole.CloudServiceReference.GetCustomerNumerRequest GetCustomerNumerRequest;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(ClientConsole.CloudServiceReference.GetCustomerNumerRequest GetCustomerNumerRequest) {
            this.GetCustomerNumerRequest = GetCustomerNumerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CustomerBizTalkService.GetCustomerNumerResponse", Order=0)]
        public ClientConsole.CloudServiceReference.GetCustomerNumerResponse GetCustomerNumerResponse;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(ClientConsole.CloudServiceReference.GetCustomerNumerResponse GetCustomerNumerResponse) {
            this.GetCustomerNumerResponse = GetCustomerNumerResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WcfService_CustomerBizTalkServiceChannel : ClientConsole.CloudServiceReference.WcfService_CustomerBizTalkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfService_CustomerBizTalkServiceClient : System.ServiceModel.ClientBase<ClientConsole.CloudServiceReference.WcfService_CustomerBizTalkService>, ClientConsole.CloudServiceReference.WcfService_CustomerBizTalkService {
        
        public WcfService_CustomerBizTalkServiceClient() {
        }
        
        public WcfService_CustomerBizTalkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfService_CustomerBizTalkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_CustomerBizTalkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_CustomerBizTalkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.CloudServiceReference.Operation_1Response ClientConsole.CloudServiceReference.WcfService_CustomerBizTalkService.Operation_1(ClientConsole.CloudServiceReference.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public ClientConsole.CloudServiceReference.GetCustomerNumerResponse Operation_1(ClientConsole.CloudServiceReference.GetCustomerNumerRequest GetCustomerNumerRequest) {
            ClientConsole.CloudServiceReference.Operation_1Request inValue = new ClientConsole.CloudServiceReference.Operation_1Request();
            inValue.GetCustomerNumerRequest = GetCustomerNumerRequest;
            ClientConsole.CloudServiceReference.Operation_1Response retVal = ((ClientConsole.CloudServiceReference.WcfService_CustomerBizTalkService)(this)).Operation_1(inValue);
            return retVal.GetCustomerNumerResponse;
        }
    }
}
