//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.CustomerWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerWebService.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerNumber", ReplyAction="*")]
        ClientConsole.CustomerWebService.GetCustomerNumberResponse GetCustomerNumber(ClientConsole.CustomerWebService.GetCustomerNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerNumber", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.CustomerWebService.GetCustomerNumberRequestBody Body;
        
        public GetCustomerNumberRequest() {
        }
        
        public GetCustomerNumberRequest(ClientConsole.CustomerWebService.GetCustomerNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetCustomerNumberRequestBody() {
        }
        
        public GetCustomerNumberRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.CustomerWebService.GetCustomerNumberResponseBody Body;
        
        public GetCustomerNumberResponse() {
        }
        
        public GetCustomerNumberResponse(ClientConsole.CustomerWebService.GetCustomerNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCustomerNumberResult;
        
        public GetCustomerNumberResponseBody() {
        }
        
        public GetCustomerNumberResponseBody(int GetCustomerNumberResult) {
            this.GetCustomerNumberResult = GetCustomerNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : ClientConsole.CustomerWebService.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<ClientConsole.CustomerWebService.CustomerWebServiceSoap>, ClientConsole.CustomerWebService.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.CustomerWebService.GetCustomerNumberResponse ClientConsole.CustomerWebService.CustomerWebServiceSoap.GetCustomerNumber(ClientConsole.CustomerWebService.GetCustomerNumberRequest request) {
            return base.Channel.GetCustomerNumber(request);
        }
        
        public int GetCustomerNumber(string name) {
            ClientConsole.CustomerWebService.GetCustomerNumberRequest inValue = new ClientConsole.CustomerWebService.GetCustomerNumberRequest();
            inValue.Body = new ClientConsole.CustomerWebService.GetCustomerNumberRequestBody();
            inValue.Body.name = name;
            ClientConsole.CustomerWebService.GetCustomerNumberResponse retVal = ((ClientConsole.CustomerWebService.CustomerWebServiceSoap)(this)).GetCustomerNumber(inValue);
            return retVal.Body.GetCustomerNumberResult;
        }
    }
}
